- name: Configuracion de servidores
  hosts: servers
  become: true

  tasks:

    - name: Actualizar cache de APT
      apt:
        update_cache: yes

    - name: Actualizar paquetes del sistema
      apt:
        upgrade: dist

    - name: Crear usuario itla
      user:
        name: itla
        state: present
        shell: /bin/bash

    - name: Crear carpeta app
      file:
        path: /home/ansible/app
        state: directory
        mode: '0755'

    - name: Crear archivo hola.txt
      copy:
        dest: /home/ansible/app/hola.txt
        content: "Hola desde Ansible 🚀"
        mode: '0644'

    - name: Instalar cowsay y htop
      apt:
        name:
          - cowsay
          - htop
        state: present